apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: kafka-exporter
  name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: kafka-exporter
    spec:
      containers:
        - args:
            - --kafka.server=kafka:9093
          image: danielqsj/kafka-exporter
          name: kafka-exporter
          ports:
            - containerPort: 9308
              protocol: TCP
      restartPolicy: Always
